### ISSUE TITLE
can add attr sort? 

### ISSUE THREAD

**Issue by phoenix043030** [frustra/bbcode#2]
if i convert [url]http:a.b.c[/url]  to `<a href="http:a.b.c" class="custom"></a>`, may two different result :
`<a href="http:a.b.c" class="custom"></a>`  or `<a class="custom" href="http:a.b.c" ></a>`

if can support attr sort ?

**Comment by xthexder** [comment]
I'll see if I can throw together an option for sorting output attributes. This will make the compile time slightly slower, but that doesn't always matter, especially if you're doing caching.

**Comment by xthexder** [comment]
You can now sort the output attributes by setting `compiler.SortOutputAttributes = true`
